# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"\x07\n\x05\x45mpty\"Y\n\x12RequestVoteMessage\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"\x8a\x01\n\x14\x41ppendEntriesMessage\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x14\n\x0cprevLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0bprevLogTerm\x18\x04 \x01(\x05\x12\x17\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x06.Entry\x12\x14\n\x0cleaderCommit\x18\x06 \x01(\x05\"5\n\x05\x45ntry\x12\r\n\x05index\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x03 \x03(\t\")\n\rTermIdMessage\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\"1\n\x11TermResultMessage\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0e\n\x06result\x18\x02 \x01(\x08\"/\n\x10IdAddressMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"\x1b\n\nIntMessage\x12\r\n\x05value\x18\x01 \x01(\x05\"+\n\rSetValMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1c\n\rGetValMessage\x12\x0b\n\x03key\x18\x01 \x01(\t\"(\n\x15SetValResponseMessage\x12\x0f\n\x07success\x18\x01 \x01(\x08\"7\n\x15GetValResponseMessage\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05value\x18\x02 \x01(\t2\x81\x01\n\x0bRaftService\x12\x36\n\x0bRequestVote\x12\x13.RequestVoteMessage\x1a\x12.TermResultMessage\x12:\n\rAppendEntries\x12\x15.AppendEntriesMessage\x1a\x12.TermResultMessage2\xde\x01\n\rClientService\x12!\n\x07\x43onnect\x12\x06.Empty\x1a\x0e.TermIdMessage\x12&\n\tGetLeader\x12\x06.Empty\x1a\x11.IdAddressMessage\x12\x1e\n\x07Suspend\x12\x0b.IntMessage\x1a\x06.Empty\x12\x30\n\x06SetVal\x12\x0e.SetValMessage\x1a\x16.SetValResponseMessage\x12\x30\n\x06GetVal\x12\x0e.GetValMessage\x1a\x16.GetValResponseMessageb\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_REQUESTVOTEMESSAGE = DESCRIPTOR.message_types_by_name['RequestVoteMessage']
_APPENDENTRIESMESSAGE = DESCRIPTOR.message_types_by_name['AppendEntriesMessage']
_ENTRY = DESCRIPTOR.message_types_by_name['Entry']
_TERMIDMESSAGE = DESCRIPTOR.message_types_by_name['TermIdMessage']
_TERMRESULTMESSAGE = DESCRIPTOR.message_types_by_name['TermResultMessage']
_IDADDRESSMESSAGE = DESCRIPTOR.message_types_by_name['IdAddressMessage']
_INTMESSAGE = DESCRIPTOR.message_types_by_name['IntMessage']
_SETVALMESSAGE = DESCRIPTOR.message_types_by_name['SetValMessage']
_GETVALMESSAGE = DESCRIPTOR.message_types_by_name['GetValMessage']
_SETVALRESPONSEMESSAGE = DESCRIPTOR.message_types_by_name['SetValResponseMessage']
_GETVALRESPONSEMESSAGE = DESCRIPTOR.message_types_by_name['GetValResponseMessage']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

RequestVoteMessage = _reflection.GeneratedProtocolMessageType('RequestVoteMessage', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTVOTEMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:RequestVoteMessage)
  })
_sym_db.RegisterMessage(RequestVoteMessage)

AppendEntriesMessage = _reflection.GeneratedProtocolMessageType('AppendEntriesMessage', (_message.Message,), {
  'DESCRIPTOR' : _APPENDENTRIESMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:AppendEntriesMessage)
  })
_sym_db.RegisterMessage(AppendEntriesMessage)

Entry = _reflection.GeneratedProtocolMessageType('Entry', (_message.Message,), {
  'DESCRIPTOR' : _ENTRY,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:Entry)
  })
_sym_db.RegisterMessage(Entry)

TermIdMessage = _reflection.GeneratedProtocolMessageType('TermIdMessage', (_message.Message,), {
  'DESCRIPTOR' : _TERMIDMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:TermIdMessage)
  })
_sym_db.RegisterMessage(TermIdMessage)

TermResultMessage = _reflection.GeneratedProtocolMessageType('TermResultMessage', (_message.Message,), {
  'DESCRIPTOR' : _TERMRESULTMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:TermResultMessage)
  })
_sym_db.RegisterMessage(TermResultMessage)

IdAddressMessage = _reflection.GeneratedProtocolMessageType('IdAddressMessage', (_message.Message,), {
  'DESCRIPTOR' : _IDADDRESSMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:IdAddressMessage)
  })
_sym_db.RegisterMessage(IdAddressMessage)

IntMessage = _reflection.GeneratedProtocolMessageType('IntMessage', (_message.Message,), {
  'DESCRIPTOR' : _INTMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:IntMessage)
  })
_sym_db.RegisterMessage(IntMessage)

SetValMessage = _reflection.GeneratedProtocolMessageType('SetValMessage', (_message.Message,), {
  'DESCRIPTOR' : _SETVALMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:SetValMessage)
  })
_sym_db.RegisterMessage(SetValMessage)

GetValMessage = _reflection.GeneratedProtocolMessageType('GetValMessage', (_message.Message,), {
  'DESCRIPTOR' : _GETVALMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:GetValMessage)
  })
_sym_db.RegisterMessage(GetValMessage)

SetValResponseMessage = _reflection.GeneratedProtocolMessageType('SetValResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _SETVALRESPONSEMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:SetValResponseMessage)
  })
_sym_db.RegisterMessage(SetValResponseMessage)

GetValResponseMessage = _reflection.GeneratedProtocolMessageType('GetValResponseMessage', (_message.Message,), {
  'DESCRIPTOR' : _GETVALRESPONSEMESSAGE,
  '__module__' : 'raft_pb2'
  # @@protoc_insertion_point(class_scope:GetValResponseMessage)
  })
_sym_db.RegisterMessage(GetValResponseMessage)

_RAFTSERVICE = DESCRIPTOR.services_by_name['RaftService']
_CLIENTSERVICE = DESCRIPTOR.services_by_name['ClientService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=14
  _EMPTY._serialized_end=21
  _REQUESTVOTEMESSAGE._serialized_start=23
  _REQUESTVOTEMESSAGE._serialized_end=112
  _APPENDENTRIESMESSAGE._serialized_start=115
  _APPENDENTRIESMESSAGE._serialized_end=253
  _ENTRY._serialized_start=255
  _ENTRY._serialized_end=308
  _TERMIDMESSAGE._serialized_start=310
  _TERMIDMESSAGE._serialized_end=351
  _TERMRESULTMESSAGE._serialized_start=353
  _TERMRESULTMESSAGE._serialized_end=402
  _IDADDRESSMESSAGE._serialized_start=404
  _IDADDRESSMESSAGE._serialized_end=451
  _INTMESSAGE._serialized_start=453
  _INTMESSAGE._serialized_end=480
  _SETVALMESSAGE._serialized_start=482
  _SETVALMESSAGE._serialized_end=525
  _GETVALMESSAGE._serialized_start=527
  _GETVALMESSAGE._serialized_end=555
  _SETVALRESPONSEMESSAGE._serialized_start=557
  _SETVALRESPONSEMESSAGE._serialized_end=597
  _GETVALRESPONSEMESSAGE._serialized_start=599
  _GETVALRESPONSEMESSAGE._serialized_end=654
  _RAFTSERVICE._serialized_start=657
  _RAFTSERVICE._serialized_end=786
  _CLIENTSERVICE._serialized_start=789
  _CLIENTSERVICE._serialized_end=1011
# @@protoc_insertion_point(module_scope)
